### ISSUE TITLE
Can't seem to run the demo app

### ISSUE THREAD

**Issue by courtneyconroy** [NXPNFCLinux/linux_libnfc-nci#84]
Does anyone have a bit more detail on setting this up? I just cloned the github but when I try ./nfcDemoapp it doesn't work. Is there something I am missing? This is my first time doing such a thing

**Comment by jgeslin** [comment]
Details are given in related documentation: https://www.nxp.com/docs/en/application-note/AN11697.pdf.
Which target are you using ? Raspberry Pi ?

**Comment by courtneyconroy** [comment]
We are using Raspberry Pi but we can't find a dts file to continue on with the steps

**Comment by jgeslin** [comment]
If you are using Raspberry Pi, you can use the "alternative to kernel driver" configuration. After cloning the repo, and enabling the i2c-dev driver in kernet (through raspi-config command) just do (from the linux_libnfc-nci directory):
`./bootstrap`
`./configure --enable-pn7150 --enable-alt --sysconfdir=/etc` // if using OM5578, otherwise if using OM5577 demo kit define "--enable-pn7120" instead of "--enable-pn7150
`make`
`sudo make install`
`./nfcDemoApp poll`
